FROM node:20.11.1 AS debug

WORKDIR /app

RUN rm -rf node_modules package-lock.json

# Copy package.json and tsconfig.json
COPY ./package*.json ./
COPY ./tsconfig.json ./

# Installing dependencies
RUN npm install

# Install pm2 globally
RUN npm install -g pm2

# Copying all the files in our project
COPY . .

# Exposing server port
EXPOSE 12098
EXPOSE 9229

# Declaring env
ENV NODE_ENV=development

# Starting the application with pm2
ENTRYPOINT [ "npm", "run", "build:start:pm2" ]
