services:
  fastify:
    container_name: aws-autorotate-credentials-with-electron-fastify-api
    image: aws-autorotate-credentials-with-electron-fastify-api
    working_dir: /app
    platform: linux/amd64
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile_prod
    ports:
      - 12098:12098
      - 9229:9229
    volumes:
      - ./src:/app/src
      - ./build:/app/build